"""adiciona status a charging_sessions

Revision ID: 337954a67c95
Revises: 5adc56d5c83d
Create Date: 2026-08-26 21:31:25.264524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337954a67c95'
down_revision: Union[str, None] = '5adc56d5c83d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


charging_session_status = sa.Enum(
    'pending', 'active', 'finished', 'error', name='charging_session_status'
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Linha de FK em establishments.owner_id removida daqui: falso positivo do autogenerate
    # por causa do use_alter=True no model (ela ja existe desde a migration inicial).
    # add_column com Enum novo nao cria o tipo sozinho (so create_table faz isso) - precisa
    # do create() explicito antes, senao a coluna aponta pra um tipo que nao existe no Postgres.
    charging_session_status.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'charging_sessions',
        sa.Column(
            'status',
            charging_session_status,
            server_default='pending',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charging_sessions', 'status')
    charging_session_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
