"""schema inicial

Revision ID: 6a550df89efb
Revises: 
Create Date: 2026-08-21 09:57:12.081211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a550df89efb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establishments',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('phase', sa.String(length=15), nullable=False),
    sa.Column('grid_connection_kw', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('power_limit_kw', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_establishments_owner_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chargers',
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('sems_serial', sa.String(length=64), nullable=False),
    sa.Column('model', sa.Enum('gw7k', 'gw11k', 'gw22k', name='charger_model'), nullable=False),
    sa.Column('spot_label', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('livre', 'carregando', 'problema', 'reservado', 'offline', name='charger_status'), nullable=False),
    sa.Column('nominal_power_kw', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sems_serial')
    )
    op.create_table('companies',
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('cost_center', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('avulso', 'mensal', 'trimestral', name='plan_kind'), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('free_kwh_allowance', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariff_rules',
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('days_of_week', sa.String(length=20), nullable=False),
    sa.Column('start_time_local', sa.Time(), nullable=False),
    sa.Column('end_time_local', sa.Time(), nullable=False),
    sa.Column('price_per_kwh', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('is_special', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('charger_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['charger_id'], ['chargers.id'], ),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charger_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('charger_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('power_kw', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('status', sa.Enum('livre', 'carregando', 'problema', 'reservado', 'offline', name='charger_status'), nullable=False),
    sa.ForeignKeyConstraint(['charger_id'], ['chargers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_charger_readings_charger_id_timestamp', 'charger_readings', ['charger_id', 'timestamp'], unique=False)
    op.create_table('invoices',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('owner', 'customer', name='user_role'), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('vehicle_model', sa.String(length=100), nullable=True),
    sa.Column('rfid_virtual_id', sa.String(length=64), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub'),
    sa.UniqueConstraint('rfid_virtual_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('charging_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('charger_id', sa.UUID(), nullable=False),
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('energy_kwh', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('tariff_rule_id', sa.UUID(), nullable=True),
    sa.Column('tariff_rate_applied', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('plan_discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('free_minutes_applied', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['charger_id'], ['chargers.id'], ),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.ForeignKeyConstraint(['tariff_rule_id'], ['tariff_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_charging_sessions_establishment_id_started_at', 'charging_sessions', ['establishment_id', 'started_at'], unique=False)
    op.create_index('ix_charging_sessions_user_id_started_at', 'charging_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('queue_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('billing_cycle_start', sa.Date(), nullable=False),
    sa.Column('billing_cycle_end', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('queue_entries')
    op.drop_index('ix_charging_sessions_user_id_started_at', table_name='charging_sessions')
    op.drop_index('ix_charging_sessions_establishment_id_started_at', table_name='charging_sessions')
    op.drop_table('charging_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('invoices')
    op.drop_index('ix_charger_readings_charger_id_timestamp', table_name='charger_readings')
    op.drop_table('charger_readings')
    op.drop_table('alerts')
    op.drop_table('tariff_rules')
    op.drop_table('plans')
    op.drop_table('companies')
    op.drop_table('chargers')
    op.drop_table('establishments')
    # ### end Alembic commands ###
