"""adiciona coordenadas do estabelecimento e reservas antecipadas

Revision ID: 7830e4378920
Revises: be7ace01a916
Create Date: 2026-08-27 13:54:17.086530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7830e4378920'
down_revision: Union[str, None] = 'be7ace01a916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('charger_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'fulfilled', 'cancelled', 'no_show', name='reservation_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['charger_id'], ['chargers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('establishments', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('establishments', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('establishments', 'longitude')
    op.drop_column('establishments', 'latitude')
    op.drop_table('reservations')
    # ### end Alembic commands ###
