"""adiciona reserva de fila em queue_entries

Revision ID: c07edbff2c80
Revises: 337954a67c95
Create Date: 2026-08-26 21:43:51.279476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07edbff2c80'
down_revision: Union[str, None] = '337954a67c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # FK em establishments.owner_id removida daqui: falso positivo do autogenerate por
    # causa do use_alter=True no model (ja existe desde a migration inicial - ver tambem
    # 337954a67c95, mesmo problema).
    op.add_column('queue_entries', sa.Column('reserved_charger_id', sa.UUID(), nullable=True))
    op.add_column('queue_entries', sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        'fk_queue_entries_reserved_charger_id', 'queue_entries', 'chargers',
        ['reserved_charger_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_queue_entries_reserved_charger_id', 'queue_entries', type_='foreignkey')
    op.drop_column('queue_entries', 'reserved_at')
    op.drop_column('queue_entries', 'reserved_charger_id')
    # ### end Alembic commands ###
