"""adiciona formas de pagamento aceitas pelo estabelecimento

Revision ID: c18be676ce47
Revises: 517ddb444cd5
Create Date: 2026-08-27 14:45:08.430514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18be676ce47'
down_revision: Union[str, None] = '517ddb444cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'establishments',
        sa.Column(
            'accepted_payment_methods_csv',
            sa.String(length=120),
            nullable=False,
            server_default='',
        ),
    )
    op.alter_column('establishments', 'accepted_payment_methods_csv', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('establishments', 'accepted_payment_methods_csv')
    # ### end Alembic commands ###
