"""torna unico indice charger_id timestamp em charger_readings

Revision ID: f2e7e9fc9d48
Revises: c07edbff2c80
Create Date: 2026-08-26 22:18:47.246940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e7e9fc9d48'
down_revision: Union[str, None] = 'c07edbff2c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # FK em establishments.owner_id removida daqui: falso positivo do autogenerate por
    # causa do use_alter=True no model (mesmo problema ja visto em 337954a67c95/c07edbff2c80).
    op.drop_index('ix_charger_readings_charger_id_timestamp', table_name='charger_readings')
    op.create_index('ix_charger_readings_charger_id_timestamp', 'charger_readings', ['charger_id', 'timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_charger_readings_charger_id_timestamp', table_name='charger_readings')
    op.create_index('ix_charger_readings_charger_id_timestamp', 'charger_readings', ['charger_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###
