"""adiciona limites de precificacao dinamica ao estabelecimento

Revision ID: fd107b73830a
Revises: f2e7e9fc9d48
Create Date: 2026-08-27 01:32:32.251513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd107b73830a'
down_revision: Union[str, None] = 'f2e7e9fc9d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: o autogenerate tambem detectou uma FK ausente em establishments.owner_id.
    # Confirmado com inspect(engine).get_foreign_keys() no Postgres real: a constraint NAO
    # existe hoje. A migration inicial (6a550df89efb) so declara
    # ForeignKeyConstraint(..., use_alter=True) dentro do proprio create_table, sem um
    # op.create_foreign_key() separado depois - e por isso o Postgres nunca recebeu o ALTER
    # TABLE. Uma migration anterior (337954a67c95) ja tinha topado com esse mesmo falso
    # "detectado" e presumiu, errado, que a FK ja existia - nao existe. Removida daqui de
    # proposito por nao ter relacao com estes dois campos novos; corrigir merece sua propria
    # migration revisada (checar dado orfao em owner_id antes de criar a constraint).
    op.add_column('establishments', sa.Column('max_increase_pct', sa.Numeric(precision=5, scale=2), nullable=False, server_default='20.00'))
    op.add_column('establishments', sa.Column('max_decrease_pct', sa.Numeric(precision=5, scale=2), nullable=False, server_default='20.00'))
    op.alter_column('establishments', 'max_increase_pct', server_default=None)
    op.alter_column('establishments', 'max_decrease_pct', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('establishments', 'max_decrease_pct')
    op.drop_column('establishments', 'max_increase_pct')
    # ### end Alembic commands ###
